// the precomputed-stats helpers: URL and Item-id rules, the collection lookup, the window rule, and the
// shaping of Parquet rows into the rows a live run produces. the Parquet files are tiny closed-form
// fixtures (__fixtures__/stats, regenerated by make_stats_fixture.sh); the live check is skipped
// offline (ERDDAP_OFFLINE=1).
import { describe, expect, it, beforeEach } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  hasPrecomputed, inWindow, itemId, planRun, parseStatsCollection, precomputedIndex, precomputedPath, precomputedUrl, provenanceUrl,
  readPrecomputed, resetPrecomputedIndex, shapeRows, sourceLabel, usePrecomputed, windowCovered, loadPrecomputed,
  parseProvenance, lobeAxes, type LobeAxes,
} from './precomputed'
import { GAZETTEER_BASE, GAZETTEER_FALLBACK } from './gazetteer'
import { fmtDay } from './sentence'

const FIX = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '__fixtures__/stats')
const bytes = (f: string) => { const b = fs.readFileSync(path.join(FIX, f)); return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength) as ArrayBuffer }
const collection = JSON.parse(fs.readFileSync(path.join(FIX, 'collection.json'), 'utf8'))
const D = (s: string) => Date.parse(`${s}T00:00:00Z`)

describe('names', () => {
  it('builds stats/<dataset>/<variable>/<place>.parquet and keeps the colon', () => {
    expect(precomputedPath('dhw_5km', 'CRW_SST', 'NMS:FKNMS')).toBe('stats/dhw_5km/CRW_SST/NMS:FKNMS.parquet')
    expect(precomputedUrl('dhw_5km', 'CRW_SST', 'NMS:FKNMS'))      // the bucket: the storage host's 302 has no CORS
      .toBe('https://s3.us-east-1.amazonaws.com/oceanmetrics.io-public/gazetteer/stats/dhw_5km/CRW_SST/NMS:FKNMS.parquet')
    expect(precomputedUrl('noaa_aoml_seascapes_8day', 'CLASS', 'PSGID:939', 'https://x/g/'))
      .toBe('https://x/g/stats/noaa_aoml_seascapes_8day/CLASS/PSGID:939.parquet')
  })
  it('names the provenance sibling and the STAC item like stats.ts', () => {
    expect(provenanceUrl('https://x/stats/a/b/NMS:C.parquet')).toBe('https://x/stats/a/b/NMS:C.provenance.json')
    expect(itemId('dhw_5km', 'CRW_SST', 'NMS:FKNMS')).toBe('dhw_5km_CRW_SST_NMS-FKNMS')
  })
})

describe('what exists', () => {
  const index = parseStatsCollection(collection)
  it('reads the item links of stats/collection.json', () => {
    expect(index.has('dhw_5km_CRW_SST_NMS-FKNMS')).toBe(true)
    expect(index.size).toBe(4)
  })
  it('answers per (dataset, variable, place), not per list of ids', () => {
    expect(hasPrecomputed(index, 'dhw_5km', 'CRW_SST', 'NMS:FKNMS')).toBe(true)
    expect(hasPrecomputed(index, 'noaa_aoml_seascapes_8day', 'CLASS', 'PSGID:939')).toBe(true)
    expect(hasPrecomputed(index, 'dhw_5km', 'CRW_BAA', 'NMS:FKNMS')).toBe(false)     // variable not published for it
    expect(hasPrecomputed(index, 'dhw_5km', 'CRW_SST', 'MRGID:8439')).toBe(false)    // place not listed
    expect(hasPrecomputed(null, 'dhw_5km', 'CRW_SST', 'NMS:FKNMS')).toBe(false)
  })
  it('ignores a malformed collection', () => {
    expect(parseStatsCollection(null).size).toBe(0)
    expect(parseStatsCollection({ links: [{ rel: 'item' }, { rel: 'root', href: 'a.json' }] }).size).toBe(0)
  })
  describe('the cached index', () => {
    beforeEach(resetPrecomputedIndex)
    it('fetches once and caches', async () => {
      let calls = 0
      const f = async () => { calls++; return new Response(JSON.stringify(collection)) }
      const a = await precomputedIndex(f), b = await precomputedIndex(f)
      expect(calls).toBe(1)
      expect(a).toBe(b)
      expect(hasPrecomputed(a, 'dhw_5km', 'CRW_SST', 'NMS:FKNMS')).toBe(true)
    })
    it('a failure is an empty index, cached (no retry noise)', async () => {
      let calls = 0
      const f = async () => { calls++; throw new Error('down') }
      expect((await precomputedIndex(f)).size).toBe(0)
      await precomputedIndex(f)
      expect(calls).toBe(1)
    })
  })
})

describe('the run decision', () => {
  it('uses precomputed rows for a listed grid only', () => {
    expect(usePrecomputed({ protocol: 'griddap', has: true })).toBe(true)
    expect(usePrecomputed({ protocol: 'griddap', has: false })).toBe(false)
    expect(usePrecomputed({ protocol: 'tabledap', has: true })).toBe(false)
  })
  const cov = { start: '2025-10-07', end: '2026-10-06' }
  it('covers a window that starts inside the file, even if it runs past the last refresh', () => {
    expect(windowCovered(cov, { start: '2026-09-07', end: '2026-10-06' })).toBe(true)
    expect(windowCovered(cov, { start: '2026-10-01', end: '2026-10-08' })).toBe(true)
  })
  it('does not cover a window before the file, after it, or an empty file', () => {
    expect(windowCovered(cov, { start: '2025-09-01', end: '2025-10-30' })).toBe(false)
    expect(windowCovered(cov, { start: '2026-10-07', end: '2026-10-08' })).toBe(false)
    expect(windowCovered(null, { start: '2026-10-01', end: '2026-10-08' })).toBe(false)
  })
  it('words the strip header: the series is precomputed, the map is the live slice', () => {
    expect(sourceLabel({ through: '2026-10-06', mapDate: '2026-10-08' }, fmtDay)).toBe('precomputed to 6 Oct 2026 · map: live 8 Oct 2026')
    expect(sourceLabel({ through: '2026-10-06' }, fmtDay)).toBe('precomputed to 6 Oct 2026 · map: loading…')
    expect(sourceLabel({ through: '2026-10-06', failed: true }, fmtDay)).toBe('precomputed to 6 Oct 2026 · map: unavailable')
  })
  it('has a compact form for a phone: no words, the shared year dropped', () => {
    expect(sourceLabel({ through: '2026-10-06', mapDate: '2026-10-08' }, fmtDay, true)).toBe('precomputed 6 Oct · map 8 Oct')
    expect(sourceLabel({ through: '2025-12-30', mapDate: '2026-01-02' }, fmtDay, true)).toBe('precomputed 30 Dec 2025 · map 2 Jan 2026')
    expect(sourceLabel({ through: '2026-10-06' }, fmtDay, true)).toBe('precomputed 6 Oct 2026')
    expect(sourceLabel({ through: '2026-10-06', failed: true }, fmtDay, true)).toBe('precomputed 6 Oct 2026 · map failed')
  })
})

describe('provenance: the label, the fallback last step and the axes', () => {
  const axes: LobeAxes[] = [{ bbox: [-83.1, 24.3, -80.1, 25.7], lon: [-83.125, -83.075], lat: [25.675, 25.625] },
                { bbox: [179.2, -1, 180, 1], lon: [179.225], lat: [0.975, 0.925] }]
  const j = { generated: '2026-10-06T21:23:38Z', end_datetime: '2026-10-05T12:00:00Z', axes, sql: '…' }
  it('reads generated, end_datetime and the per-lobe axes', () => {
    expect(parseProvenance(j)).toEqual({ asOf: '2026-10-06', end: '2026-10-05T12:00:00Z', axes })
  })
  it('a provenance from before the axes, or malformed axes, gives null axes (the app asks ERDDAP)', () => {
    expect(parseProvenance({ generated: '2026-09-15T00:00:00Z' })).toEqual({ asOf: '2026-09-15', end: null, axes: null })
    expect(parseProvenance({ ...j, axes: [{ bbox: [0, 0, 1, 1], lon: [], lat: [1] }] }).axes).toBeNull()
    expect(parseProvenance({ ...j, axes: [{ bbox: [0, 0, 1], lon: [1], lat: [1] }] }).axes).toBeNull()
    expect(parseProvenance({ ...j, axes: [{ bbox: [0, 0, 1, 1], lon: ['1'], lat: [1] }] }).axes).toBeNull()
    expect(parseProvenance(null)).toEqual({ asOf: null, end: null, axes: null })
  })
  it('lobeAxes: used only when they describe these lobes, in order', () => {
    const lobes = axes.map((a) => ({ bbox: [...a.bbox] }))
    expect(lobeAxes(axes, lobes)).toBe(axes)
    expect(lobeAxes(axes, [{ bbox: [-83.1 + 1e-12, 24.3, -80.1, 25.7] }, lobes[1]])).toBe(axes)   // a JSON round trip
    expect(lobeAxes(axes, lobes.slice(0, 1))).toBeNull()                                        // another lobe count
    expect(lobeAxes(axes, [lobes[1], lobes[0]])).toBeNull()                                     // another order
    expect(lobeAxes(axes, [{ bbox: [-83.2, 24.3, -80.1, 25.7] }, lobes[1]])).toBeNull()         // the polygon moved
    expect(lobeAxes(null, lobes)).toBeNull()
  })
})

describe('planRun: what a run loads', () => {
  const coverage = { start: '2025-10-07', end: '2026-10-06' }
  const grid = { protocol: 'griddap', has: true, coverage }
  it('precomputed + a window inside the range: the whole series is the strip, the map is ONE slice', () => {
    expect(planRun(grid, { start: '2026-09-07', end: '2026-10-06' }, '2026-10-06T12:00:00Z'))
      .toEqual({ strip: 'precomputed', map: 'slice', slice: '2026-10-06' })
  })
  it('the slice is the window end, but never past the dataset\'s last step', () => {
    expect(planRun(grid, { start: '2026-09-09', end: '2026-10-08' }, '2026-10-07T12:00:00Z').slice).toBe('2026-10-07')   // the file lags the server
    expect(planRun(grid, { start: '2026-01-01', end: '2026-01-30' }, '2026-10-07T12:00:00Z').slice).toBe('2026-01-30')   // a brushed past window
    // extent unknown (ERDDAP's info did not answer): never past the file's last day, a step the server
    // holds; the window end could be past the dataset's end and 404 ("greater than the axis maximum")
    expect(planRun(grid, { start: '2026-09-09', end: '2026-10-08' }).slice).toBe('2026-10-06')
    expect(planRun(grid, { start: '2026-01-01', end: '2026-01-30' }).slice).toBe('2026-01-30')
  })
  it('a window that starts before the file takes the full live path (whole window slab)', () => {
    expect(planRun(grid, { start: '2025-09-01', end: '2025-10-30' }, '2026-10-06T12:00:00Z'))
      .toEqual({ strip: 'live', map: 'window', slice: null })
  })
  it('a window after the file, an empty file, no file, or a tabledap target is live too', () => {
    const live = { strip: 'live', map: 'window', slice: null }
    expect(planRun(grid, { start: '2026-10-07', end: '2026-10-08' })).toEqual(live)
    expect(planRun({ ...grid, coverage: null }, { start: '2026-09-07', end: '2026-10-06' })).toEqual(live)
    expect(planRun({ ...grid, has: false }, { start: '2026-09-07', end: '2026-10-06' })).toEqual(live)
    expect(planRun({ ...grid, protocol: 'tabledap' }, { start: '2026-09-07', end: '2026-10-06' })).toEqual(live)
  })
})

describe('rows from a Parquet file', () => {
  it('continuous: the columns of stats_daily.sql, date as epoch ms, plain numbers', async () => {
    const { rows, coverage } = await readPrecomputed(bytes('continuous.parquet'), 'continuous')
    expect(coverage).toEqual({ start: '2026-01-01', end: '2026-01-06' })
    expect(rows).toHaveLength(6)
    expect(Object.keys(rows[0])).toEqual(['date', 'n', 'mean', 'mean_wt', 'sd', 'min', 'max', 'p10', 'p90', 'weight_sum'])
    expect(rows[0]).toEqual({ date: D('2026-01-01'), n: 10, mean: 20, mean_wt: 20.5, sd: 0.5, min: 19, max: 22, p10: 19.5, p90: 21.5, weight_sum: 9.5 })
    expect(typeof rows[0].n).toBe('number')                  // not a bigint
    expect(rows[5].mean_wt).toBe(25.5)
  })
  it('restricts to the window, inclusive, and reports the coverage of the whole file', async () => {
    const { rows, coverage } = await readPrecomputed(bytes('continuous.parquet'), 'continuous', { start: '2026-01-02', end: '2026-01-04' })
    expect(rows.map((r) => r.date)).toEqual([D('2026-01-02'), D('2026-01-03'), D('2026-01-04')])
    expect(coverage).toEqual({ start: '2026-01-01', end: '2026-01-06' })
  })
  it('without a window the rows are the whole series, and inWindow() takes the window out of it', async () => {
    const { rows, bytes: n } = await readPrecomputed(bytes('continuous.parquet'), 'continuous')
    expect(n).toBe(bytes('continuous.parquet').byteLength)
    expect(rows).toHaveLength(6)
    expect(inWindow(rows, { start: '2026-01-02', end: '2026-01-04' }).map((r) => r.date)).toEqual([D('2026-01-02'), D('2026-01-03'), D('2026-01-04')])
    expect(inWindow(rows, { start: '2026-01-06', end: '2026-02-01' })).toHaveLength(1)    // a window running past the file's end
    expect(inWindow(rows, { start: '2027-01-01', end: '2027-01-30' })).toEqual([])
  })
  it('categorical: inWindow() keeps every class of a day', async () => {
    const { rows } = await readPrecomputed(bytes('categorical.parquet'), 'categorical')
    expect(inWindow(rows, { start: '2026-01-05', end: '2026-01-09' }).map((r) => [r.date, r.class]))
      .toEqual([[D('2026-01-09'), 1], [D('2026-01-09'), 2]])
  })
  it('a window outside the file has no rows', async () => {
    expect((await readPrecomputed(bytes('continuous.parquet'), 'continuous', { start: '2027-01-01', end: '2027-01-30' })).rows).toEqual([])
  })
  it('categorical: renames frac_area / pct_cells to the live fraction / percent_cells, sorted by date then class', async () => {
    const { rows } = await readPrecomputed(bytes('categorical.parquet'), 'categorical')
    expect(rows).toEqual([
      { date: D('2026-01-01'), class: 1, n: 6, weight: 7.5, fraction: 0.75, percent_cells: 60 },
      { date: D('2026-01-01'), class: 2, n: 4, weight: 2.5, fraction: 0.25, percent_cells: 40 },
      { date: D('2026-01-09'), class: 1, n: 5, weight: 5, fraction: 0.5, percent_cells: 50 },
      { date: D('2026-01-09'), class: 2, n: 5, weight: 5, fraction: 0.5, percent_cells: 50 },
    ])
    for (const d of ['2026-01-01', '2026-01-09'])
      expect(rows.filter((r) => r.date === D(d)).reduce((a, r) => a + r.fraction, 0)).toBeCloseTo(1, 12)
  })
  it('keeps nulls null (a day with no valid cells has null statistics, as live)', () => {
    const [r] = shapeRows([{ date: new Date(D('2026-01-01')), n: 0n, mean: null, mean_wt: undefined }], 'continuous')
    expect(r.n).toBe(0); expect(r.mean).toBeNull(); expect(r.mean_wt).toBeNull()
  })
})

describe('loadPrecomputed', () => {
  it('reads a file over fetch, falls back from the bucket to the storage host', async () => {
    const urls: string[] = []
    const real = globalThis.fetch
    globalThis.fetch = (async (u: any) => {
      urls.push(String(u))
      return String(u).startsWith(GAZETTEER_FALLBACK) ? new Response('', { status: 503 }) : new Response(bytes('continuous.parquet'))
    }) as any
    try {
      const r = await loadPrecomputed(precomputedUrl('dhw_5km', 'CRW_SST', 'NMS:TEST'), 'continuous', { start: '2026-01-01', end: '2026-01-03' })
      expect(r.rows).toHaveLength(3)
      expect(urls).toHaveLength(2)
      expect(urls[1]).toContain('storage.oceanmetrics.io')
    } finally { globalThis.fetch = real }
  })
})

describe('the published file (live)', async () => {
  const online = !process.env.ERDDAP_OFFLINE && await fetch(GAZETTEER_BASE + 'stats/collection.json', { signal: AbortSignal.timeout(15_000) }).then((r) => r.ok, () => false)
  it.skipIf(!online)('FKNMS CRW_SST is listed and reads into the live row shape', async () => {
    resetPrecomputedIndex()
    const index = await precomputedIndex()
    expect(hasPrecomputed(index, 'dhw_5km', 'CRW_SST', 'NMS:FKNMS')).toBe(true)
    const { rows, coverage } = await loadPrecomputed(precomputedUrl('dhw_5km', 'CRW_SST', 'NMS:FKNMS'), 'continuous')
    expect(rows.length).toBeGreaterThan(300)
    expect(coverage!.end > coverage!.start).toBe(true)
    expect(Object.keys(rows[0])).toEqual(['date', 'n', 'mean', 'mean_wt', 'sd', 'min', 'max', 'p10', 'p90', 'weight_sum'])
    expect(rows[0].mean_wt).toBeGreaterThan(10)
  }, 30_000)
})
